#
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
#Fichero de configuración para trabajar en modo desarrollo. 
#Si la aplicación se arranca como launch-dev se utilizará esta configuración de la aplicación
#En esta configuración el servidor embebido estará en modo "gestionado", se registrará en BC y desde ahí se podrán cargar contenedores, gestionar procesos y tareas humanas
#server configuration
server.address=0.0.0.0
server.port=8090

cxf.path=/rest

#GENERAL, trazado

#trazas propias
logging.level.us.dit.humanTasks.service.controller.TasksController=DEBUG
logging.level.us.dit.humanTasks.service.controller.QuestionnaireController=DEBUG
logging.level.us.dit.humanTasks.service.controller.QuestionnaireResponseController=DEBUG
logging.level.us.dit.humanTasks.service.controller.FormController=DEBUG
logging.level.us.dit.humanTasks.service.model.FhirTasksDAO=DEBUG
logging.level.us.dit.humanTasks.service.model.TasksDAO=DEBUG
logging.level.us.dit.humanTasks.service.model.FhirQuestionnaireDAO=DEBUG
logging.level.us.dit.humanTasks.service.model.FhirQuestionnaireResponseDAO=DEBUG
logging.level.us.dit.humanTasks.service.services.kie.KieUtil=DEBUG
logging.level.us.dit.humanTasks.service.conf.SystemPropertiesInjector=DEBUG;
#trazas hapi fhir
logging.level.ca.uhn.fhir.context.FhirContext=DEBUG

#trazas spring
#logging.level.org.springframework.security=TRACE
#trazas de la api kie
logging.level.org.kie.server.client.KieServicesClient=DEBUG
logging.level.org.kie.server.client.KieServicesFactory=DEBUG
logging.level.org.kie.server.client.KieServerFactoryService=DEBUG
logging.level.org.kie.server.client.UserTaskServicesClient=DEBUG
logging.level.org.kie.server.client.admin.UserTaskAdminServicesClient=DEBUG
logging.level.org.kie.server.services.rest.KieServerRestImpl=DEBUG
logging.level.org.jbpm.services.api.RuntimeDataService=DEBUG
#configuraciÃ³n consola h2
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-allow-others=true

#propiedades del sistema para la configuracion del servidor
#utilizar el prefijo system.properties y a continuacion nombre de la propiedad y valor, si en el starter no estÃ¡ ya la propiedad disponible
#kie server config
kieserver.serverId=healthcareTasks-dev
kieserver.serverName=healthcareTasks Dev
#kieserver.location=http://localhost:8090/rest/server

###############################################################################
###                      IMPORTACIÓN DE KIE SERVERS                         ###
###############################################################################
#para que se pueda acceder desde BC alojado al servidor kie de mi app
kieserver[0].location=http://host.docker.internal:8090/rest/server
kieserver[0].user=kieserver
kieserver[0].pwd=kieserver1!

###############################################################################

#Los clientes java deben usar esta url del servidor, y no la de kieserver.location, porque la aplicación corre en el host y no en docker
#client.kieserver.location=http://localhost:8090/rest/server
#BC config, configuración del controlador
#https://docs.redhat.com/en/documentation/red_hat_process_automation_manager/7.7/html/managing_and_monitoring_kie_server/kie-server-configure-server-managed-by-central-proc#kie-server-configure-server-managed-by-central-proc
#controllerUser tiene que estar configurado en BC con el rol rest-all
kieserver.controllers=http://localhost:8080/business-central/rest/controller
## el usuario controllerUser tiene que estar dado de alta en business central con el rol rest-all, porque debe permitir acceder a la api del controlador
system.properties.org.kie.server.controller.pwd=controllerUser
system.properties.org.kie.server.controller.user=controllerUser
#otras propiedades para la ejecución
#Permite realizar peticiones al motor de procesos en nombre de un usuario distinto al que se está conectando. Trabajo en modo agente.
system.properties.org.kie.server.bypass.auth.user=true
#system.properties.org.jbpm.ht.admin.user=medico
#grupo encargado de gestionar las tareas humanas, Impresdincible para gestionar tareas humanas de este motor desde BC
system.properties.org.jbpm.ht.admin.group=admin
system.properties.org.jbpm.task.cleanup.enabled=false

#kie server capabilities
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.jbpm.enabled=true
kieserver.jbpmui.enabled=true
kieserver.casemgmt.enabled=true
#kieserver.prometheus.enabled=true
#esta no estaba por defecto, la de swagger
kieserver.swagger.enabled=true



#jbpm configuration
jbpm.executor.enabled=false
#jbpm.executor.retries=5
#jbpm.executor.interval=3
#jbpm.executor.threadPoolSize=1
#jbpm.executor.timeUnit=SECONDS

#mÃ¡s info en https://www.baeldung.com/spring-boot-h2-database
#data source configuration
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.url=jdbc:h2:./target/spring-boot-jbpm
#si lo quisieramos como fichero???
#spring.datasource.url=jdbc:h2:file:./target/spring-boot-jbpm   
spring.datasource.driver-class-name=org.h2.Driver
#para facilitar la monitorizaciÃ³n de la base de datos
#activa la url http://localhost:8090/h2-console que permitirÃ¡ ver la base de datos
spring.h2.console.enabled=true

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#transaction manager configuration
spring.jta.narayana.transaction-manager-id=1

#banner
spring.banner.location=classpath:banner.txt

#fhir
fhir.server.base=http://localhost:8888/fhir

#variables para los tests

#identificador del cuestionario fhir pasado como entrada a las tareas humanas de test
test.questionnaireid=1
#nombre del contenedor desplegado en el servidor kie embebido
test.containerid=human-tasks-management_1.0.0-SNAPSHOT
#nombre del proceso que contiene una tarea asignada al role wbadmin sin temporizador
test.roleprocessWithoutTimer=HumanTasksManagement.TareaARolSinTimer
#nombre del proceso que asigna una tarea al usuario que lo inicia
test.userprocess=HumanTasksManagement.TareaAUsuario
#nombre del proceso que contiene una tarea asignada al role wbadmin
test.roleprocessHigh=HumanTasksManagement.TareaARolUrgente
test.roleprocessMedium=HumanTasksManagement.TareaARolMedia
test.roleprocessLow=HumanTasksManagement.TareaARolLeve


